User interface milestone 2
Byabasaija/tic_tac_toe_game pull request #3
Opened 2020-12-03 20:05 UTC by HillaryOkello

In this milestone, we created the user interface for the tic-tac-toe game.

2020-12-03 21:12 UTC, blackpintz requested changes
# Status: Changes Required

## Hello team 😄,

**Your project shows great initiative 👏. However, a few things need to be implemented before it can be approved.**

1). **Basic Hint.**
![image](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png)

2). **The main goal of this milestone is to draw a design of the game. So you need to show the following,**

-  How the game will tell which player's turn it is. 

- How the game will ask the player to select the available moves.

- How the game board will look like after a move has been played.

- Describe an invalid move and show how the game will inform the player that they have made an invalid move.

- You have shown how the game will inform of a win, but you haven't described a winning move scenario. You can use a game board for this.

- You have shown how the game will inform of a draw but you haven't described a  game draw scenario. You can use a game board for this.

3). **You need to define a loop to describe that you are aware that are some repetitive tasks are gonna be placed in here. Something like this,**

```ruby
game_on = true

# initial instructions for player

while game_on
  # loop for each move
  
  if winner # and/or draw 
    game_on = false
  end
end
```

## Happy coding 🥂 

**PS: You can reach me on slack (Rose Wanjohi).**

2020-12-04 13:25 UTC, mcrd25 requested changes
# Changes Required 🔍 

Hi Team! 👋 

A few changes required but you've done a great job mocking the flow of the game!

### Required changes
- Your game asks the player to select from available moves
- Check my review comments

***Please makes changes and submit another review request.
If you have any questions, let me know here or email (preferably) or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

If you liked my review, consider upskilling me on linkedin. And don't be afraid to connect. [My LinkedIn](https://www.linkedin.com/in/mayadouglas/)

*Happy coding 😄,*
**[--Maya Douglas](mayacdouglas.com)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-12-04 13:25 UTC, mcrd25 commented on bin/main.rb
> +    puts 'You Drew'
Prefer message: It's a Draw

2020-12-04 13:25 UTC, mcrd25 commented on bin/main.rb
> +token = gets.chomp!
[OPTIONAL]
How do we know which player this is for?

2020-12-04 13:25 UTC, mcrd25 commented on bin/main.rb
> +puts "Welcome to Pascal and Hillary's tic-tac-toe game"
/you are missing the line to make this file executable.
`#!/usr/bin/env ruby` needs to be added and the right permissions need to be added. Please see this [screenshot](requirements_screenshots)

2020-12-04 15:22 UTC, voscarmv requested changes
# Impressive work, team. 💻 👀 ✨ 

- Good job implementing the changes requested previously.

## However, there are some changes required 👀 🧰 🔨 🔧 

- Let's improve the user interface by implementing a game loop. Use all the methods you've developed so far, but now add a game loop structure such as this, to have a basic flow for the players to follow:

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-12-04 16:07 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great job guys, well done with the project.

now you can move to the next milestone, this milestone is approved.

## Happy Coding :tophat:

2020-12-07 06:30 UTC, merged